@startuml

skinparam dip 100

title Single Activity - Configuration changes

actor User

User -> Activity: App started
activate Activity

Activity -> Activity: call onCreate(null)
activate Activity
deactivate Activity

Activity -> Activity: call onStart()
activate Activity
deactivate Activity

Activity -> Activity: call onResume()
activate Activity
deactivate Activity

User -> Activity: Device rotated

Activity -> Activity: call onConfigurationChanged()
activate Activity
deactivate Activity
deactivate Activity

@enduml