@startuml

ObserverA --> Subject: registerObserver
ObserverB --> Subject: registerObserver

Subject --> Subject: notifyObservers
activate Subject
Subject --> ObserverA: update
Subject --> ObserverB: update
deactivate Subject


@enduml